Minorversion 68 release
intuit/QuickBooks-V3-DotNET-SDK pull request #284
Opened 2023-01-31 06:45 UTC by sujitharamadass

Schema changes and Minorversion change 68

2023-01-31 08:34 UTC, nimisha84 commented on IPPDotNetDevKitCSV3/Test/Intuit.Ipp.Test/SDKV3Test/Appsettings.json
> +    "AccessToken": "eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIn0..xQL-ii6CDe8s1snK5DgqcQ.YgBti3dLVsOhJxZRmZ2BXXA68wF35pKb3M2ATGD2q9AgIPnEH8Z1SGw_fX3MbJRTvm41OxBWvdcRaPcy4s1kJUdvLVDvpBS-I0ZC4YpqIbW
remove these tokens please

2023-01-31 08:35 UTC, nimisha84 commented on IPPDotNetDevKitCSV3/Test/Intuit.Ipp.Test/SDKV3Test/TokenStore.json
> +    "AccessToken": "eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIn0..xQL-ii6CDe8s1snK5DgqcQ.YgBti3dLVsOhJxZRmZ2BXXA68wF35pKb3M2ATGD2q9AgIPnEH8Z1SGw_fX3MbJRTvm41OxBWvdcRaPcy4s1kJUdvLVDvpBS-I0ZC4YpqIbW
remove these please

2023-01-31 08:35 UTC, nimisha84 requested changes
Remove the tokens and commit again. Rest looks good. Thanks

2023-01-31 11:44 UTC, sujitharamadass commented on IPPDotNetDevKitCSV3/Test/Intuit.Ipp.Test/SDKV3Test/Appsettings.json
> +    "AccessToken": "eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIn0..xQL-ii6CDe8s1snK5DgqcQ.YgBti3dLVsOhJxZRmZ2BXXA68wF35pKb3M2ATGD2q9AgIPnEH8Z1SGw_fX3MbJRTvm41OxBWvdcRaPcy4s1kJUdvLVDvpBS-I0ZC4YpqIbW
Tokens removed

2023-01-31 11:44 UTC, sujitharamadass commented on IPPDotNetDevKitCSV3/Test/Intuit.Ipp.Test/SDKV3Test/TokenStore.json
> +    "AccessToken": "eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIn0..xQL-ii6CDe8s1snK5DgqcQ.YgBti3dLVsOhJxZRmZ2BXXA68wF35pKb3M2ATGD2q9AgIPnEH8Z1SGw_fX3MbJRTvm41OxBWvdcRaPcy4s1kJUdvLVDvpBS-I0ZC4YpqIbW
Tokens removed

2023-01-31 22:36 UTC, nimisha84 approved these changes

2023-02-01 17:37 UTC, nimisha84 approved these changes

2023-02-01 17:53 UTC, nimisha84 approved these changes

2023-02-01 17:56 UTC, merged